services:
    client:
      container_name: frontend-client
      build:
        context: .
        dockerfile: ./Dockerfile
        # tags:
        #   - "nalius/nalius:client"
      restart: always
      ports:
        - 4200:4200
      volumes:
        - ./client/:/app:cached
volumes:
  db-data:
